version: '3.8'
services:
  haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: shareit-haproxy
    ports:
      - "8080:8080"
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    deploy:
      replicas: 2 #2 instances of gateway will be created
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=${TZ}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name:
      shareit-server
    ports:
      - "9090:9090"
      - "5005:5005" #debugging port
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      - TZ=${TZ}

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - TZ=${TZ}
    volumes:
      - shareit-db-data:/var/lib/postgresql/data
volumes:
  shareit-db-data:

