version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name:
      shareit-gateway
    ports:
      - "8080:8080"
      - "5006:5006" #debugging port
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5006,server=y,suspend=n

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name:
      shareit-server
    ports:
      - "9090:9090"
      - "5005:5005" #debugging port
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n

  db:
    image: postgres:13.7-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
    volumes:
      - shareit-db-data:/var/lib/postgresql/data
volumes:
  shareit-db-data: